graph LR
    subgraph Legenda
        hardware[Hardware]
        interface>Interface]
        file[(Local Storage)]
        services([Services])
        program((Programa))
    end

    subgraph Solution
        direction LR

        subgraph Linux Systems Operarating
            datalogger([Process Worker's])-->server
            datalogger([Process Worker's])--> files[(logs files)]
            ConfigFile[(Config. file)] --> datalogger([Process Worker's])
            server([MQTT NETWORK \n Interface])-->internet
            internet([internet])

            subgraph Interface
                USB1
                USB2
                USBn
                BLUETOOTH
            end
            USB1>USB1] ---> datalogger
            USB2>USB2] ---> datalogger
            USBn>USBn] ---> datalogger
            BLUETOOTH>BLUETOOTH] --> datalogger
        end

        subgraph Sensores
            s1[Sensor 1] --> USB1
            s2[Sensor 2] --> USB2
            s3[Sensor 3] --> BLUETOOTH
            s4[Sensor n] --> USBn
        end

        internet --> brocker
        subgraph Cloud processing 
            brocker((brocker))
        end
    end

    
