graph LR
    subgraph Legenda
        hardware[Hardware]
        interface>Interfaces]
        file[(Arquivos)]
        services([Serviços])
        program((Programa))
    end

    subgraph Solução
        direction LR

        subgraph PFI-Hardware
            circuit[Detector de energia]
        end

        subgraph Raspberry PI
            datalogger([Datalogger])-->files
            files[(files)]-->server
            server([Web File Server])-->hotspot
            hotspot([Hotspot])

            subgraph Interface
                USB1
                USB2
                BLUETOOTH
                GPIO
            end
            circuit --> GPIO
            USB1>USB1] --> datalogger
            USB2>USB2] --> datalogger
            BLUETOOTH>BLUETOOTH] --> datalogger
            
            GPIO>GPIO] --> service-pfi([Power Fail service])
        end

        subgraph Sensores
            s1[Sensor 1] --> USB1
            s2[Sensor 2] --> USB2
            s3[Sensor 3] --> BLUETOOTH
        end

        hotspot --> iot-pos-processing
        subgraph Pós processamento
            iot-pos-processing((iot-pos-processing))
        end
    end
